### ISSUE TITLE
zc-zookeeper-static not necessarily needed

### ISSUE THREAD

**Issue by spladug** [mozilla-services/zktools#5]
As far as I can tell, `zc-zookeeper-static` is just an alternative package for the ZooKeeper python bindings. For users that get the binding through another package (e.g. Debian's `python-zookeeper`) it seems unfortunate to require `zc-zookeeper-static`.

I looked for some way to specify a dependency that can be filled by multiple packages (hoping to take advantage of `python-zookeeper`'s manual egg info) but couldn't find any.  `zc.zk`'s docs say "Because this binding is packaged a number of different ways, it isn't listed as a distribution requirement." which is one way of doing it I guess. So I guess I'm throwing my hands up and wondering if you guys have a preference of solutions.

**Comment by bbangert** [comment]
At the moment, this is true. I say that because it seems there's a patch for the zookeeper binding that prevents a memory leak that is included in Ubuntu's python zookeeper binding, but didn't get into the distribution. We were thinking of including this patch (if it passes tests) in the zc-zookeeper-static someday. As it isn't currently the case though, I think removing the dep and making it clear in the docs (maybe with another exception upon import telling the user the problem) is fine.

**Comment by bbangert** [comment]
Fixed this in trunk, I updated the docs to mention that it needs to be installed.

**Comment by spladug** [comment]
Awesome, thanks a bunch!
